(() => {
  "use strict";
  const $ = (id) => document.getElementById(id);
  const state = { config:{}, socket:null, reconnect:1000, provider:"local", scene:"ambient", jarvisState:"sleeping", media:null, cards:[], timers:[], metrics:{local:[],"gemini-live":[]}, health:{}, lastHealth:0 };
  const els = Object.fromEntries(["clock","date","temperature","weatherSummary","weatherLocation","calendar","calendarCount","news","provider","status","statusEyebrow","transcript","userText","assistantText","cards","timersPanel","timers","timerCount","media","mediaArt","mediaSource","mediaTitle","mediaArtist","mediaProgress","topology","topologyLabel","components","metrics","metricRows","connection","sceneLabel","presence","announcer"].map(id=>[id,$(id)]));
  const escape = (value) => { const span=document.createElement("span"); span.textContent=String(value??""); return span.innerHTML; };

  function tickClock(){const now=new Date();els.clock.textContent=now.toLocaleTimeString(state.config.locale||undefined,{hour:"2-digit",minute:"2-digit",hour12:false});els.clock.dateTime=now.toISOString();els.date.textContent=now.toLocaleDateString(state.config.locale||undefined,{weekday:"long",day:"numeric",month:"long"}).toUpperCase();resolveScene();tickTimers();tickMedia()}
  async function loadBootstrap(){try{const response=await fetch("/api/mirror/bootstrap");if(!response.ok)throw new Error();const data=await response.json();state.config=data.config||{};renderCalendar(data.calendar||[]);renderNews(data.news||[]);await loadWeather()}catch{renderCalendar([]);renderNews([])}}
  async function loadWeather(){const {latitude,longitude,location}=state.config;if(!Number.isFinite(latitude)||!Number.isFinite(longitude))return;try{const url=new URL("https://api.open-meteo.com/v1/forecast");url.search=new URLSearchParams({latitude,longitude,current:"temperature_2m,weather_code",timezone:"auto"});const data=await (await fetch(url)).json();els.temperature.textContent=`${Math.round(data.current.temperature_2m)}°`;els.weatherSummary.textContent=weatherLabel(data.current.weather_code);els.weatherLocation.textContent=location||""}catch{els.weatherSummary.textContent="Weather unavailable"}}
  const weatherLabel=(code)=>code===0?"Clear":code<4?"Partly cloudy":code<50?"Low visibility":code<70?"Rain":code<80?"Snow":code<96?"Showers":"Thunderstorm";
  function renderCalendar(items){els.calendarCount.textContent=`${items.length} EVENTS`;els.calendar.classList.toggle("muted",!items.length);els.calendar.innerHTML=items.length?items.slice(0,5).map(item=>`<div class="list-item"><time>${escape(item.when)}</time><div><strong>${escape(item.title)}</strong><small>${escape(item.location||"")}</small></div></div>`).join(""):"No upcoming events"}
  function renderNews(items){els.news.classList.toggle("muted",!items.length);els.news.innerHTML=items.length?items.slice(0,5).map(item=>`<div class="list-item"><time>${escape(item.source||"NEWS")}</time><div><strong>${escape(item.title)}</strong></div></div>`).join(""):"No headlines"}

  function connect(){const protocol=location.protocol==="https:"?"wss:":"ws:";const url=new URL(state.config.websocketUrl||`${protocol}//${location.host}/ws`);url.searchParams.set("client","mirror");try{state.socket=new WebSocket(url)}catch{return scheduleReconnect()}state.socket.addEventListener("open",()=>{state.reconnect=1000;els.connection.classList.add("online");els.connection.innerHTML="<i></i>MSI ONLINE"});state.socket.addEventListener("message",event=>{try{handleEvent(JSON.parse(event.data))}catch{}});state.socket.addEventListener("close",()=>{els.connection.classList.remove("online");els.connection.innerHTML="<i></i>MSI OFFLINE";setJarvisState("disconnected");scheduleReconnect()});state.socket.addEventListener("error",()=>state.socket?.close())}
  function scheduleReconnect(){setTimeout(connect,state.reconnect);state.reconnect=Math.min(10000,state.reconnect*2)}
  function handleEvent(event){if(!event||typeof event!=="object")return;if(event.type==="state")setJarvisState(event.state);if(event.type==="status")setJarvisState(statusState(event.data),event.data);if(event.type==="amplitude")document.documentElement.style.setProperty("--amp",Math.max(0,Math.min(1,Number(event.value)||0)));if(event.type==="provider"){state.provider=event.provider==="gemini-live"?"gemini-live":"local";els.provider.textContent=state.provider==="gemini-live"?"GEMINI LIVE":"LOCAL INTELLIGENCE"}if(event.type==="transcript"){setTranscript(event.role,event.text);if(event.role==="user"&&event.is_final!==false)parseTimer(event.text)}if(event.type==="token")setTranscript("assistant",els.assistantText.textContent+String(event.token||""));if(event.type==="response"){setTranscript("user",event.user);setTranscript("assistant",event.assistant);deriveCard(event)}if(event.type==="latency")recordMetrics(event.metrics||{});if(event.type==="health")applyHealth(event.components||event);if(event.type==="card")addCard(event.card||event);if(event.type==="timer")consumeTimerEvent(event);if(event.type==="media")applyMedia(event);if(event.type==="presence")applyPresence(event);if(event.type==="face_cue")document.body.dataset.expression=event.expression||"neutral"}
  const statusState=(value)=>{const text=String(value||"").toLowerCase();if(text.includes("listen"))return"listening";if(text.includes("transcrib")||text.includes("think"))return"thinking";if(text.includes("speak"))return"speaking";if(text.includes("error"))return"error";if(text.includes("disconnect"))return"disconnected";return"sleeping"};
  function setJarvisState(value,label){state.jarvisState=value==="listening-followup"?"listening":String(value||"sleeping");document.body.dataset.state=state.jarvisState;els.status.textContent=label?String(label).replace(/\.+$/,""):state.jarvisState;els.statusEyebrow.textContent=state.jarvisState==="sleeping"?"SYSTEM READY":"VOICE CHANNEL ACTIVE";els.announcer.textContent=`Jarvis ${els.status.textContent}`;if(state.jarvisState==="listening"){els.userText.textContent="";els.assistantText.textContent=""}resolveScene()}
  function setTranscript(role,text){if(role==="user")els.userText.textContent=String(text||"");else els.assistantText.textContent=String(text||"");els.transcript.hidden=!(els.userText.textContent||els.assistantText.textContent)}

  function resolveScene(){const hour=new Date().getHours();const night=hour>=Number(state.config.nightStartHour??23)||hour<Number(state.config.nightEndHour??6);const scene=state.media?.isPlaying?"music":["listening","thinking","speaking"].includes(state.jarvisState)?"conversation":night?"night":"ambient";if(scene!==state.scene){state.scene=scene;document.body.dataset.scene=scene;els.sceneLabel.textContent=`${scene.toUpperCase()} SCENE`}}
  function addCard(card){const safe={id:String(card.id||Date.now()),kind:String(card.kind||"info"),title:String(card.title||"Jarvis"),subtitle:String(card.subtitle||card.value||""),expires:Date.now()+Math.max(1000,Number(card.lifetime||15000))};state.cards=[safe,...state.cards.filter(item=>item.id!==safe.id)].slice(0,3);renderCards()}
  function deriveCard(event){const query=String(event.user||"").toLowerCase();if(/weather|forecast|temperature|rain/.test(query))addCard({kind:"weather",title:els.temperature.textContent,subtitle:els.weatherSummary.textContent});}
  function renderCards(){const now=Date.now();state.cards=state.cards.filter(card=>card.expires>now);els.cards.innerHTML=state.cards.map(card=>`<article class="card"><small>${escape(card.kind)}</small><strong>${escape(card.title)}</strong><span>${escape(card.subtitle)}</span></article>`).join("")}

  function loadTimers(){try{state.timers=JSON.parse(localStorage.getItem("jarvis-standalone-timers-v1")||"[]").filter(timer=>timer.endsAt>Date.now())}catch{state.timers=[]}}
  function saveTimers(){try{localStorage.setItem("jarvis-standalone-timers-v1",JSON.stringify(state.timers))}catch{}}
  function consumeTimerEvent(event){if(event.action==="cancel"){state.timers=state.timers.filter(timer=>timer.id!==String(event.id));saveTimers();return renderTimers()}const duration=Number(event.durationMs||event.duration_ms||Number(event.seconds)*1000);const endsAt=Number(event.endsAt||event.ends_at)||Date.now()+duration;if(endsAt>Date.now()){state.timers.push({id:String(event.id||Date.now()),label:String(event.label||"Timer"),endsAt,repeatMs:Number(event.repeatMs||0)});saveTimers();renderTimers()}}
  function parseTimer(text){const normalized=String(text||"").toLowerCase();if(!/(timer|countdown|จับเวลา)/.test(normalized))return;const units={second:1000,seconds:1000,minute:60000,minutes:60000,hour:3600000,hours:3600000,"วินาที":1000,"นาที":60000,"ชั่วโมง":3600000};let duration=0;for(const match of normalized.matchAll(/(\d+(?:\.\d+)?)\s*(seconds?|minutes?|hours?|วินาที|นาที|ชั่วโมง)/g))duration+=Number(match[1])*units[match[2]];if(duration)consumeTimerEvent({durationMs:duration,label:"Voice timer"})}
  function tickTimers(){let changed=false;for(const timer of state.timers){if(timer.endsAt<=Date.now()){els.announcer.textContent=`${timer.label} complete`;addCard({kind:"timer",title:timer.label,subtitle:"Complete",lifetime:30000});sendFaceCue("excited","timer");if(timer.repeatMs){timer.endsAt=Date.now()+timer.repeatMs}else timer.done=true;changed=true}}if(changed){state.timers=state.timers.filter(timer=>!timer.done);saveTimers()}renderTimers()}
  function remaining(ms){const total=Math.max(0,Math.ceil(ms/1000)),m=Math.floor(total/60),s=total%60;return`${m}:${String(s).padStart(2,"0")}`}
  function renderTimers(){els.timersPanel.hidden=!state.timers.length;els.timerCount.textContent=`${state.timers.length} ACTIVE`;els.timers.innerHTML=state.timers.map(timer=>`<div class="timer-row"><span>${escape(timer.label)}</span><strong>${remaining(timer.endsAt-Date.now())}</strong></div>`).join("")}

  function applyMedia(event){const item=event.item||event.track||event;state.media={title:String(item.title||item.name||"Unknown track"),artist:String(item.artist||event.artist||(Array.isArray(item.artists)?item.artists.map(a=>a.name||a).join(", "):"")),image:String(event.image||item.image||item.album?.images?.[0]?.url||""),source:String(event.source||"media"),isPlaying:Boolean(event.isPlaying??event.is_playing??event.playing),progress:Number(event.progressMs||event.progress_ms||0),duration:Number(item.durationMs||item.duration_ms||event.durationMs||0)};sendFaceCue(state.media.isPlaying?"music":"neutral","media");renderMedia();resolveScene()}
  function tickMedia(){if(state.media?.isPlaying)state.media.progress=Math.min(state.media.duration||Infinity,state.media.progress+1000);renderMedia()}
  function renderMedia(){if(!state.media){els.media.hidden=true;return}els.media.hidden=!state.media.isPlaying;els.mediaArt.src=/^https?:/.test(state.media.image)?state.media.image:"";els.mediaSource.textContent=state.media.source.toUpperCase();els.mediaTitle.textContent=state.media.title;els.mediaArtist.textContent=state.media.artist;els.mediaProgress.max=state.media.duration||100;els.mediaProgress.value=state.media.progress}
  function applyPresence(event){els.presence.textContent=event.present?`${String(event.profile||event.user||"OWNER").toUpperCase()} PRESENT`:"PRIVATE MODE"}

  function recordMetrics(metrics){const clean={};for(const [key,value] of Object.entries(metrics))if(Number.isFinite(Number(value)))clean[key]=Number(value);state.metrics[state.provider].push(clean);state.metrics[state.provider]=state.metrics[state.provider].slice(-60);renderMetrics()}
  const percentile=(values,p)=>{if(!values.length)return null;const sorted=[...values].sort((a,b)=>a-b);return sorted[Math.min(sorted.length-1,Math.ceil(values.length*p)-1)]};
  function renderMetrics(){const rows=[];for(const provider of ["gemini-live","local"]){const values=state.metrics[provider].map(item=>item.total_roundtrip_ms).filter(Number.isFinite);if(values.length)rows.push(`<div class="metric-row"><strong>${provider==="gemini-live"?"CLOUD":"LOCAL"}</strong><span>p50 ${Math.round(percentile(values,.5))}ms</span><span>p95 ${Math.round(percentile(values,.95))}ms</span></div>`)}els.metrics.hidden=!rows.length;els.metricRows.innerHTML=rows.join("")}
  async function pollHealth(){try{const started=performance.now(),health=await(await fetch("/health",{cache:"no-store"})).json();applyHealth({msi:health.status==="ok",pi:true,phone:health.phone_connected!==false,microphone:Boolean(health.audio_available),speaker:Boolean(health.audio_available),gemini:Boolean(health.gemini_configured),ollama:Boolean(health.ollama_available)});state.health.networkMs=Math.round(performance.now()-started)}catch{applyHealth({...state.health,msi:false})}}
  function applyHealth(health){state.health={...state.health,...health};state.lastHealth=Date.now();const relevant=[{name:"msi",ok:state.health.msi!==false},{name:"pi",ok:true},{name:"phone",ok:state.health.phone!==false},{name:"gemini",ok:state.provider!=="gemini-live"||state.health.gemini!==false},{name:"ollama",ok:state.provider!=="local"||state.health.ollama!==false},{name:"microphone",ok:state.health.microphone!==false},{name:"speaker",ok:state.health.speaker!==false}];const fault=relevant.some(item=>!item.ok)||(state.health.networkMs||0)>2500;els.topology.hidden=!fault;els.topologyLabel.textContent=fault?"ATTENTION":"NOMINAL";els.components.innerHTML=relevant.map(item=>`<span class="component ${item.ok?"":"offline"}">${escape(item.name)}</span>`).join("")}

  function sendFaceCue(expression,source){if(state.socket?.readyState===WebSocket.OPEN)state.socket.send(JSON.stringify({action:"client_event",event:{type:"face_cue",expression,source}}))}

  document.addEventListener("visibilitychange",()=>{if(!document.hidden)pollHealth()});
  loadTimers();tickClock();setInterval(tickClock,1000);setInterval(renderCards,1000);setInterval(pollHealth,15000);loadBootstrap().finally(()=>{connect();pollHealth()});
  window.JarvisMirror={handleEvent,parseTimer,addCard};
})();
